[package]
name = "toynn"
version = "0.1.0"
authors = ["RC James Harlow <git@james.harlow.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
